# Generated by Django 3.2.3 on 2022-01-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
